spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://localhost:3306/property_management
    username: root
    password: root

  jpa:
    hibernate:
      driver: com.mysql.cj.jdbc.Driver
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: false  
    show-sql: true
logging:
  file:
    name: spring-boot.log
jwt:
  secret: eyJ0eXA6da93b4aiOiJKV1QiLCJhbGciOiJSUzI1NiIsI6da93b4amtpZCI6Im5PbzNaR7d97HJPRFhFSzFqS1doWHNsSFJfS1hFZy000d3abc983fJ9
  exp: 86400000